#!/bin/bash
echo "running cmake_vtkm.sh"
echo "currently loaded modules on p901"
module list
rm -rf install
mkdir install
echo " cmake -DBUILD_SHARED_LIBS=ON -DCMAKEINSTALL_PREFIX=${PWD}/install  -DVTKm_ENABLE_EXAMPLES=ON -DVTKm_ENABLE_BENCHMARKS=ON -DVTKm_ENABLE_OPENMP=ON -DVTKm_ENABLE_RENDERING=ON DVTKm_ENABLE_TESTING=ON ../vtk-m"
cmake -DBUILD_SHARED_LIBS=ON -DCMAKEINSTALL_PREFIX=${PWD}/install  -DVTKm_ENABLE_EXAMPLES=ON -DVTKm_ENABLE_BENCHMARKS=ON -DVTKm_ENABLE_OPENMP=ON -DVTKm_ENABLE_RENDERING=ON DVTKm_ENABLE_TESTING=ON ../vtk-m
